version: "3.4"

services:
  config-server:
    container_name: config-server
    image: ${DOCKER_REGISTRY-}config-server:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .dockerenv
    ports:
      - "32520:80"
      - "32521:443"