spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USER}
    password: ${env.DATABASE_PASSWORD}
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true


server:
  port: ${env.PORT}
  error:
    whitelabel:
      enabled: false

app:
  config:
    account:
      account-number:
        length: ${env.ACCOUNT_NUMBER_LENGTH}
    access-token-expire-minutes: ${env.ACCESS_TOKEN_EXPIRE_MINUTES}
    public-key: ${env.PUBLIC_KEY}
    private-key: ${env.PRIVATE_KEY}
    superuser:
      username: ${env.SUPERUSER_USERNAME}
      email: ${env.SUPERUSER_EMAIL}
      first-name: ${env.SUPERUSER_FIRST_NAME}
      last-name: ${env.SUPERUSER_LAST_NAME}
      password: ${env.SUPERUSER_PASSWORD}
